### ISSUE TITLE
Peer-to-peer code review - Awesome book's review

### ISSUE THREAD

**Issue by mullenlucas** [Ademola-coding/Awesome-book#4]
Hello Ademola, nice code !

- I would kindly suggest to delete old branches once a successful pull-request has been made so as to keep the repository cleaner
- I would also like to suggest to include the main/master branch in github pages so it is easier to see the final product

Other than that, great code, congratulations !

**Comment by rebaz36** [comment]
# Code Review

## Great work @Ademola-coding 

- it'd be nice if you could deploy your project, it's a simple and easy task and it allows the users to review your projects easier and better.
